
-- DANGER: this is NOT how to do it in the real world.
-- You should NEVER EVER check user data into Git!

insert into "prompts" ("question")
values
  ('Words to describe your grandma'),
  ('Nothing is better than ___ in the middle of the night'),
  ('Things you do while you''re procrastinating'),
  ('___ me if you can'),
  ('Conversation killers'),
  ('Flexible things'),
  ('Presidents (first or last names)'),
  ('Things they should have taught in school'),
  ('___ made me do it'),
  ('Cities'),
  ('Terrible baby names'),
  ('Bad ideas for a tattoo'),
  ('Things your mom was right about'),
  ('I want my ___ back'),
  ('Hippie hobbies'),
  ('Say hello to my little ___'),
  ('Ain''t nobody got time for ___'),
  ('Creative names for adult toys'),
  ('Things that couples fight about'),
  ('I''d never actually ___ a ___ but I could imagine what it feels like'),
  ('Someone who is universally loved'),
  ('Pretty people'),
  ('Movies'),
  ('Excuses to leave a party'),
  ('Athletes'),
  ('Words to describe losing your virginity'),
  ('Reasons for being on Santa''s naughty list'),
  ('___ changes after you get married'),
  ('Thoughts during sex ed'),
  ('Great gifts to give yourself'),
  ('Animals are better than humans at ___'),
  ('Things you only do with your hands'),
  ('Things that are wet'),
  ('Song titles'),
  ('Foods that make your mouth water'),
  ('You shouldn''t settle for'),
  ('Honey, I ___ the kids'),
  ('Things you do when it''s warm out'),
  ('Reasons to break up with someone'),
  ('I hate that I like to ___'),
  ('Vehicles'),
  ('Things you could use to murder someone'),
  ('Excuses to call in sick'),
  ('Thank God I''m not allergic to ___'),
  ('TV shows'),
  ('A good name for a rock band'),
  ('Overcomplicated things'),
  ('Never have I ever ___ someone'),
  ('The best things in life are ___'),
  ('Controversial people'),
  ('___ is the total worst'),
  ('Good dog names'),
  ('There''s no crying in ___'),
  ('Musicians'),
  ('___ would make a good'),
  ('name for a weed flavor'),
  ('Popular phrases / slogans'),
  ('Things you shouldn''t rub on yourself'),
  ('Colleges'),
  ('I''m curious about ___'),
  ('Stuff you avoid doing'),
  ('Why would you bring up ___?'),
  ('Mediocre things'),
  ('If Italy were a movie, the title would be ___'),
  ('___ is best after ___'),
  ('Trends you don''t like'),
  ('Never trust ___'),
  ('Sports teams'),
  ('Something you need two people to do'),
  ('Things dads are good at'),
  ('___ numbs my sorrows'),
  ('Slippery things'),
  ('Items you would only purchase online'),
  ('The next thing to go on strike about'),
  ('Atheists probably don''t believe in ___ either'),
  ('___ is legal, but it shouldn''t be'),
  ('Jobs'),
  ('Instead of cash, we should exchange ___ for ___'),
  ('___, that''s gonna be a no from me dog'),
  ('Things you learn the hard way'),
  ('First world problems'),
  ('Boss Ass B*tches'),
  ('Worst things to do when you''re hungover'),
  ('Unpopular opinion, but ___ is alright by me'),
  ('Words to describe religion'),
  ('Things you should own by the time you''re 30'),
  ('Russia in one word'),
  ('Topics referenced in rap music'),
  ('Someone you wouldn''t kiss'),
  ('Things you do when you''re naked'),
  ('Terrible gifts to get on your birthday'),
  ('I couldn''t care less about ___'),
  ('Celebrities who should run for president'),
  ('Reasons for being single'),
  ('Guilty pleasures'),
  ('Women are better at ___'),
  ('Cartoon characters'),
  ('Make America ___ Again'),
  ('Things that disturb old people'),
  ('___ is better than ___'),
  ('People who are overrated'),
  ('Words to describe your ex'),
  ('Another day, another ___'),
  ('Superpowers'),
  ('Things I suck at'),
  ('Netflix and ___'),
  ('Books'),
  ('Ways to unwind'),
  ('When you''re drunk, ___ is SO MUCH BETTER'),
  ('Reasons to dread family holidays'),
  ('Proof that aliens exist'),
  ('Things that take too long'),
  ('Words to describe the last decade'),
  ('Life would suck without my ___'),
  ('No mom, ___ is not a phase'),
  ('Qualities in men'),
  ('Someone you wanna talk sh*t about'),
  ('Reasons to throw a temper tantrum'),
  ('___ gets better with age'),
  ('Sexy names'),
  ('If you can''t beat ''em, ___ ''em'),
  ('Saturdays are for (the) ___'),
  ('Things you spend too much money on'),
  ('Go ___ yourself'),
  ('Something you keep hidden'),
  ('The happiest people in the world like ___'),
  ('Once you go ___ you never go back'),
  ('Words to describe your relationship status'),
  ('Smells you enjoy')
